import { generateId } from '../ids.js';

export const customersSeed = [
  {
    id: generateId('cus'),
    email: 'amina.salah@example.com',
    firstName: 'Amina',
    lastName: 'Salah',
    phone: '+201000000001',
    locale: 'ar',
    marketingOptIn: true,
  },
  {
    id: generateId('cus'),
    email: 'omar.khaled@example.com',
    firstName: 'Omar',
    lastName: 'Khaled',
    phone: '+201000000002',
    locale: 'ar',
    marketingOptIn: false,
  },
  {
    id: generateId('cus'),
    email: 'sara.farouk@example.com',
    firstName: 'Sara',
    lastName: 'Farouk',
    phone: '+201000000003',
    locale: 'en',
    marketingOptIn: true,
  },
  {
    id: generateId('cus'),
    email: 'youssef.adel@example.com',
    firstName: 'Youssef',
    lastName: 'Adel',
    phone: '+201000000004',
    locale: 'ar',
    marketingOptIn: true,
  },
  {
    id: generateId('cus'),
    email: 'noor.ibrahim@example.com',
    firstName: 'Noor',
    lastName: 'Ibrahim',
    phone: '+201000000005',
    locale: 'ar',
    marketingOptIn: false,
  },
  {
    id: generateId('cus'),
    email: 'hana.mostafa@example.com',
    firstName: 'Hana',
    lastName: 'Mostafa',
    phone: '+201000000006',
    locale: 'ar',
    marketingOptIn: true,
  },
  {
    id: generateId('cus'),
    email: 'tarek.gamal@example.com',
    firstName: 'Tarek',
    lastName: 'Gamal',
    phone: '+201000000007',
    locale: 'en',
    marketingOptIn: false,
  },
  {
    id: generateId('cus'),
    email: 'layla.hossam@example.com',
    firstName: 'Layla',
    lastName: 'Hossam',
    phone: '+201000000008',
    locale: 'ar',
    marketingOptIn: true,
  },
];
